server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - AuthFilter

        - id: SNIPPET-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/snippet/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - AuthFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE/
          predicates:
            - Path=/auth/**

