server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: SNIPPET-SERVICE
          uri: lb://SNIPPET-SERVICE
          predicates:
            - Path=/snippet/**
          filters:
            - AuthFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
