server:
  port: 8081

spring:
  application:
    name: USER-SERVICE+
  config:
    import: configserver:http://localhost:8888

  data:
    mongodb:
      uri: ${URL}
      username: ${USERNAME}
      password: ${PASSWORD}
      database: ${DATABASE}